Gracefully handle `ErrorKind::BrokenPipe` (`public-api ... | head -n 1`)
I am not adding an integration test for this fix, because I consider
that blocked by https://github.com/Enselic/public-api/issues/95.

It is easy to manually verify this change though, just do this:

    cargo run -- --manifest-path ~/src/public-api/tests/crates/comprehensive_api/Cargo.toml | head -n 1

With the fix you get one line as expected. Without the fix you also get

    Error: Broken pipe (os error 32)