Gracefully handle `ErrorKind::BrokenPipe` (`public-api ... | head -n 1`)
So that we don't get an error when doing something like this:

    % RUSTDOCFLAGS='-Z unstable-options --output-format json' cargo +nightly doc  --manifest-path tests/crates/comprehensive_api/Cargo.toml --lib --no-deps
    % ./target/debug/public-api tests/crates/comprehensive_api/target/doc/comprehensive_api.json | head -n 1
    pub async fn comprehensive_api::functions::async_fn() -> impl Future<Output = ()>
    Error: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }