CI: Use latest version of cargo-deny and cargo-audit
To avoid CI flakiness such as

    error: error loading advisory database: parse error: \
    error parsing /home/martin/.cargo/advisory-db/crates/cap-primitives/RUSTSEC-2024-0445.md: \
    parse error: TOML parse error at line 8, column 8
      |
    8 | cvss = "CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:N/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N"
      |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    unsupported CVSS version: 4.0

because the tools got too old. The job is low-privileged so we don't
need to be paranoid. Keep shfmt at a fixed version however to avoid
changes to auto-formating.