Add `./scripts/install-toolchains-for-tests.sh` script
Which will install toolchains needed for tests. Long-term it will be
nice to get rid of this, but since this is a one-time thing, I think we
can live with it.

If a dev runs `cargo test` with missing toolchains, the dev will see
this error:

    thread 'warn_when_using_beta' panicked at '
    You must run

        ./scripts/install-toolchains-for-tests.sh

    before running tests. Or simply run

        ./scripts/run-ci-locally.sh

    to both install toolchains and run tests in one command.
    ', cargo-public-api/tests/../../test-utils/src/lib.rs:70:5